create service account for unleash
app-sre/unleash pull request #31
Opened 2022-05-04 20:05 UTC by suzana-nesic

This work is to clear the DVO alerts. Part of [APPSRE-5337](https://issues.redhat.com/browse/APPSRE-5337) and [APPSRE-4942](https://issues.redhat.com/browse/APPSRE-4942)

Signed-off-by: Suzana Nesic <snesic@redhat.com>

2022-05-04 21:06 UTC, bkez322 requested changes
This should half fix it.

The other half that is missing, is to tell the deployment to actually use the new ServiceAccount you're creating.

Example: https://github.com/app-sre/deployment-validation-operator/blob/master/deploy/openshift/operator.yaml#L72

2022-05-04 21:45 UTC, suzana-nesic commented
@bkez322 Good catch, thank you! Went ahead and added that update

2022-05-05 14:19 UTC, bkez322 commented
LGTM

2022-05-05 14:19 UTC, bkez322 approved these changes

2022-05-05 14:20 UTC, merged